import "@flowui/react/styles.scss";
import type { Metadata } from "next";
import { type PropsWithChildren } from "react";
import { Inter } from "next/font/google";
import { Column, Paper } from "@flowui/react/layout";
// import { getColorScheme } from "@/services/session/get-color-scheme";
// import { cookies } from "next/headers";
import Navbar from "@/components/navbar";
import styles from "./layout.module.scss";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export default function Layout({ children }: PropsWithChildren) {
  // const colorScheme = use(getColorScheme(cookies()));

  return (
    <html lang="en">
      <body className={clsx(inter.className, "antialiased")}>
        <Paper>
          <div className={styles.background} />
          <Navbar />
          <Column expand items="center" customClassName={styles.content}>
            {children}
          </Column>
        </Paper>
      </body>
    </html>
  );
}

// noinspection JSUnusedGlobalSymbols
export const metadata: Metadata = {
  title: {
    template: "%s - FlowUI",
    default: "FlowUI",
  },
  description: "Generated by create next app",
  applicationName: "FlowUI",
  themeColor: [
    {
      media: "(prefers-color-scheme: light)",
      color: "#f4f4f5",
    },
    {
      media: "(prefers-color-scheme: dark)",
      color: "#000",
    },
  ],
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/favicon.ico",
  },
};
