import "@flowui/react/styles.scss";
import type { Metadata } from "next";
import type { PropsWithChildren } from "react";
import { Inter } from "next/font/google";
import { Column, Paper, Row } from "@flowui/react/layout";
import Navbar from "@/components/navbar";
import SideMenu from "@/components/side-menu";

const inter = Inter({ subsets: ["latin"] });

export default function Layout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Paper customClassName="!p-0 items-center">
          <Navbar />
          <Row expand customClassName="min-h-0 container">
            <SideMenu />
            <Column expand customClassName="p-6 overflow-y-auto">
              {children}
            </Column>
          </Row>
        </Paper>
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  title: {
    template: "%s | FlowUI",
    default: "FlowUI",
  },
  description: "Generated by create next app",
  applicationName: "FlowUI",
  themeColor: [
    {
      media: "(prefers-color-scheme: light)",
      color: "#fff",
    },
    {
      media: "(prefers-color-scheme: dark)",
      color: "#000",
    },
  ],
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/favicon.ico",
  },
};
