import "@flowui/react/styles.scss";
import type { PropsWithChildren } from "react";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FlowUI",
  description: "Generated by create next app",
};

const Layout = ({ children }: PropsWithChildren) => (
  <html lang="en">
    <body className={inter.className}>{children}</body>
  </html>
);

export default Layout;
